// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package decisionlogs

import (
	"context"
)

type Querier interface {
	CreateDecisionLog(ctx context.Context, arg CreateDecisionLogParams) (DecisionLog, error)
	GetDecisionLog(ctx context.Context, decisionID string) (DecisionLog, error)
	ListDecisionLogs(ctx context.Context) ([]DecisionLog, error)
	ListDecisionLogsSearch(ctx context.Context, arg ListDecisionLogsSearchParams) ([]DecisionLog, error)
}

var _ Querier = (*Queries)(nil)
